DELETE http://localhost:3001/users/6
x-university-schema: university_harvard_university

###
DELETE http://localhost:3001/courses/3
x-university-schema: university_harvard_university

###
DELETE http://localhost:3001/courses/2/topics/6
x-university-schema: university_harvard_university

###
DELETE http://localhost:3001/courses/lectures/1
x-university-schema: university_harvard_university

###
DELETE http://localhost:3001/courses/presentations/1
x-university-schema: university_harvard_university
