GET http://localhost:3001/users?role=teacher
x-university-schema: university_harvard_university

###
GET http://localhost:3001/users/1
x-university-schema: university_harvard_university

###
GET http://localhost:3001/courses/
x-university-schema: university_harvard_university

###
GET http://localhost:3001/courses/6
x-university-schema: university_harvard_university

###
GET http://localhost:3001/courses/6/topics
x-university-schema: university_harvard_university

###
GET http://localhost:3001/courses/1/topics/2
x-university-schema: university_harvard_university

###
GET http://localhost:3001/courses/assignments/3
x-university-schema: university_harvard_university

###
GET http://localhost:3001/courses/lectures/2
x-university-schema: university_harvard_university

###
GET http://localhost:3001/courses/presentations/2
x-university-schema: university_harvard_university

###
GET http://localhost:3001/university/