GET http://localhost:3001/users?role=student
x-university-schema: university_harvard_university

###
GET http://localhost:3001/users/7
x-university-schema: university_harvard_university

###
GET http://localhost:3001/courses/
x-university-schema: university_harvard_university

###
GET http://localhost:3001/courses/6
x-university-schema: university_harvard_university

###
GET http://localhost:3001/courses/6/topics
x-university-schema: university_harvard_university

###
GET http://localhost:3001/courses/6/topics/14
x-university-schema: university_harvard_university

###
GET http://localhost:3001/courses/assignments/3
x-university-schema: university_harvard_university

###
GET http://localhost:3001/courses/lectures/2
x-university-schema: university_harvard_university

###
GET http://localhost:3001/courses/presentations/2
x-university-schema: university_harvard_university

###
GET http://localhost:3001/university/

###
GET http://localhost:3001/dashboard/summary/
x-university-schema: university_harvard_university