GET http://localhost:3001/students/
x-university-schema: university_harvard_university

###
GET http://localhost:3001/students/1
x-university-schema: university_harvard_university

###
GET http://localhost:3001/courses/
x-university-schema: university_harvard_university

###
GET http://localhost:3001/courses/1
x-university-schema: university_harvard_university

###
GET http://localhost:3001/teachers/
x-university-schema: university_harvard_university

###
GET http://localhost:3001/teachers/1
x-university-schema: university_harvard_university

###
GET http://localhost:3001/university/