### Signup
POST http://localhost:3001/users/
Content-Type: application/json
x-university-schema: university_harvard_university

{
  "email": "Odil@gmail.com",
  "password": "123123",
  "name": "Odil",
  "role": "student",
  "age": "21",
  "phoneNumber": "12347290",
  "studentId": "1234567891"
}


###
POST http://localhost:3001/courses/
x-university-schema: university_harvard_university
Content-Type: application/json

{
    "name": "Dancing",
    "description": "Dancing is maybe the most fun Course"
}

###
POST http://localhost:3001/teachers/
x-university-schema: university_harvard_university
Content-Type: application/json

{
    "name": "Teacher Eshmatov",
    "email": "Eshmatov@gmail.com",
    "phoneNumber": "94621064251",
    "courseIds": ["1", "7"]
}

###
POST http://localhost:3001/university/
Content-Type: application/json

{
    "name": "Cambridge University"
}