### Signup
POST http://localhost:3001/users/
Content-Type: application/json
x-university-schema: university_harvard_university

{
  "email": "abduqayumovm1@gmail.com",
  "password": "123123",
  "name": "muhammad",
  "role": "admin",
  "age": "21",
  "phoneNumber": "+998944101551",
  "studentId": "123456",
  "courseIds": ["1"]
}


###
POST http://localhost:3001/courses/
x-university-schema: university_harvard_university
Content-Type: application/json

{
    "name": "Math",
    "description": "Math is not that difficult subject"
}

###
POST http://localhost:3001/teachers/
x-university-schema: university_harvard_university
Content-Type: application/json

{
    "name": "Teacher Eshmatov",
    "email": "Eshmatov@gmail.com",
    "phoneNumber": "94621064251",
    "courseIds": ["1", "7"]
}

###
POST http://localhost:3001/courses/6/topics
x-university-schema: university_harvard_university
Content-Type: application/json

{
    "title": "Topic 2",
    "description": "Topic 2 description"
}

###
POST http://localhost:3001/courses/coursesTopics
x-university-schema: university_harvard_university
Content-Type: application/json

{
    "title": "CourseWithTopic1",
    "description": "CourseWithTopic1 description",
    "topicTitle": "Topic 1",
    "topicDescription": "Topic 1 description"
}

###
POST http://localhost:3001/courses/6/topics/14/assignments
x-university-schema: university_harvard_university
Content-Type: application/json

{
    "title": "Topic 14",
    "description": "Topic 14 description",
    "due_date": "2023-01-01 12:00:00",
    "images": [
        {"title": "image1", "url": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"},
        {"title": "image2", "url": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"}
    ]
}

###
POST http://localhost:3001/courses/create/lecture
x-university-schema: university_harvard_university
Content-Type: application/json

{
    "title": "lectures 3",
    "content": "lectures description",
    "video": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "image": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
}

###
POST http://localhost:3001/courses/6/topics/14/presentations
x-university-schema: university_harvard_university
Content-Type: application/json

{
    "title": "Topic 3",
    "file_url": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
}

###
POST http://localhost:3001/university/
Content-Type: application/json

{
    "name": "Cambridge University"
}

