PUT http://localhost:3001/users/1
x-university-schema: university_harvard_university
Content-Type: application/json

{
    "name": "Student Eshmatov",
    "age": null,
    "phoneNumber": "50155251",
    "courseIds": ["1", "5"]
}

###
PUT http://localhost:3001/courses/1
x-university-schema: university_harvard_university
Content-Type: application/json

{
    "name": "IT",
    "description": "IT iis the art of creating software."
}

###
PUT http://localhost:3001/teachers/1
x-university-schema: university_harvard_university
Content-Type: application/json

{
    "name": "Teacher Eshmatov",
    "age": "25",
    "email": "Teacher@gmail.com",
    "phoneNumber": "45044251",
    "courseIds": ["1", "3"]
}